from flask import Flask, Response
from PIL import Image, ImageDraw, ImageFont
import io
import random

app = Flask(__name__)

def generate_image(img_id=1):
    """Generate a simple image with text and customizable parameters"""
    # Create a new image with RGB mode and white background
    width, height = 400, 200
    image = Image.new('RGB', (width, height), color='white')
    
    # Create a drawing object
    draw = ImageDraw.Draw(image)
    
    # Define different colors and shapes based on image ID
    colors = ['lightblue', 'lightgreen', 'lightcoral', 'lightyellow', 'lightpink']
    shapes = ['rectangle', 'ellipse', 'polygon']
    fill_color = colors[img_id % len(colors)]
    
    # Draw a shape based on image ID
    shape_type = shapes[img_id % len(shapes)]
    if shape_type == 'rectangle':
        draw.rectangle([50, 50, 350, 150], fill=fill_color, outline='blue', width=3)
    elif shape_type == 'ellipse':
        draw.ellipse([50, 50, 350, 150], fill=fill_color, outline='red', width=3)
    elif shape_type == 'polygon':
        draw.polygon([(200, 50), (350, 100), (200, 150), (50, 100)], fill=fill_color, outline='green', width=3)
    
    # Add text to the image
    try:
        # Try to use a default font
        font = ImageFont.truetype("arial.ttf", 24)
    except IOError:
        # If arial.ttf is not available, use default font
        font = ImageFont.load_default()
    
    text = f"Hello from Flask API! Image #{img_id}"
    # Get text size for centering
    bbox = draw.textbbox((0, 0), text, font=font)
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]
    
    # Calculate position to center the text
    x = (width - text_width) // 2
    y = (height - text_height) // 2
    
    # Draw the text
    draw.text((x, y), text, fill='black', font=font)
    
    # Save image to a BytesIO object
    img_io = io.BytesIO()
    image.save(img_io, 'PNG')
    img_io.seek(0)
    
    return img_io

@app.route('/image', methods=['GET'])
def get_image():
    """Route that returns an image with default ID"""
    img_io = generate_image(1)
    
    # Return the image as a response with appropriate content type
    return Response(
        img_io.getvalue(),
        mimetype='image/png',
        headers={'Content-Disposition': 'inline; filename=image.png'}
    )

@app.route('/image/<int:img_id>', methods=['GET'])
def get_image_by_id(img_id):
    """Route that returns an image with specified ID"""
    img_io = generate_image(img_id)
    
    # Return the image as a response with appropriate content type
    return Response(
        img_io.getvalue(),
        mimetype='image/png',
        headers={'Content-Disposition': f'inline; filename=image_{img_id}.png'}
    )

@app.route('/images', methods=['GET'])
def get_multiple_images():
    """Route that returns multiple images as a composite image"""
    # Generate multiple images and combine them into one
    images = []
    for i in range(1, 9):  # Create 8 sub-images
        img_io = generate_image(i)
        img = Image.open(img_io)
        images.append(img)
    
    # Create a 2x4 grid of images (2 rows, 4 columns)
    final_width = 400 * 4  # 4 columns
    final_height = 200 * 2  # 2 rows
    composite_image = Image.new('RGB', (final_width, final_height), color='white')
    
    for idx, img in enumerate(images):
        row = idx // 4
        col = idx % 4
        composite_image.paste(img, (col * 400, row * 200))
    
    # Save composite image to BytesIO
    img_io = io.BytesIO()
    composite_image.save(img_io, 'PNG')
    img_io.seek(0)
    
    return Response(
        img_io.getvalue(),
        mimetype='image/png',
        headers={'Content-Disposition': 'inline; filename=multi_images.png'}
    )

@app.route('/', methods=['GET'])
def index():
    """Simple homepage"""
    return '''
    <h1>Flask Image API</h1>
    <p>Visit <a href="/image">/image</a> to see an image generated by this API.</p>
    <p>Visit <a href="/image/1">/image/1</a> to <a href="/image/8">/image/8</a> to see images with different IDs.</p>
    <p>Visit <a href="/images">/images</a> to see a composite image with multiple images in a grid.</p>
    <p>Visit <a href="/test">/test</a> to see a test page displaying multiple images.</p>
    '''

@app.route('/test', methods=['GET'])
def test_page():
    """Test page to display multiple images"""
    try:
        with open('test_multiple_images.html', 'r') as f:
            html_content = f.read()
        return Response(html_content, mimetype='text/html')
    except FileNotFoundError:
        return Response('<h1>Test HTML file not found</h1><p>Please create test_multiple_images.html file in the project root directory.</p>', mimetype='text/html')

# Run the application on the port specified by Render
if __name__ == '__main__':
    import os
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=False)
